import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next appsadfasdf',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <meta
          name="theme-color"
          content="#c7d6da"
          media="(prefers-color-scheme: dark)"
        />
        <meta
          name="theme-color"
          content="#191a1a"
          media="(prefers-color-scheme: light)"
        />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
